/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.zhaw.it.prog2.wordcloud;

import javafx.application.Application;

import javax.swing.*;

public class App {
    public static void main(String[] args) {
        Application.launch(MainWindow.class, args);
    }
}

